export enum LicenseDurationEnum {
  LESS_THAN_1_MONTH = 'LESS_THAN_1_MONTH',
  ONE_TO_3_MONTHS = 'ONE_TO_3_MONTHS',
  THREE_TO_6_MONTHS = 'THREE_TO_6_MONTHS',
  MORE_THAN_6_MONTHS = 'MORE_THAN_6_MONTHS',
  OTHER = 'OTHER',
}

