export enum SpecializationEnum {
  // Mental Health & Psychology
  PSYCHOLOGY = 'PSYCHOLOGY',
  PERINATAL_PSYCHOLOGY = 'PERINATAL_PSYCHOLOGY',
  PSYCHIATRY = 'PSYCHIATRY',
  COUNSELLING = 'COUNSELLING',
  COUPLE_THERAPY = 'COUPLE_THERAPY',
  FAMILY_THERAPY = 'FAMILY_THERAPY',

  // Coaching
  PERSONAL_COACHING = 'PERSONAL_COACHING',
  PARENTAL_COACHING = 'PARENTAL_COACHING',
  ONTOLOGICAL_COACHING = 'ONTOLOGICAL_COACHING',
  CAREER_COACHING = 'CAREER_COACHING',
  EXECUTIVE_COACHING = 'EXECUTIVE_COACHING',
  LEADERSHIP_COACHING = 'LEADERSHIP_COACHING',

  // Early Childhood & Development
  NEUROSCIENCE_PARENTHOOD = 'NEUROSCIENCE_PARENTHOOD',
  DOULA = 'DOULA',
  MIDWIFERY = 'MIDWIFERY',
  CHILDCARE = 'CHILDCARE',
  LACTATION = 'LACTATION',
  PARENTING = 'PARENTING',
  INFANT_SLEEP = 'INFANT_SLEEP',
  ADOPTION_SUPPORT = 'ADOPTION_SUPPORT',
  FERTILITY_SUPPORT = 'FERTILITY_SUPPORT',

  // Education & Development
  PSYCHOPEDAGOGY = 'PSYCHOPEDAGOGY',
  OCCUPATIONAL_THERAPY = 'OCCUPATIONAL_THERAPY',

  // Medical
  NEONATOLOGY = 'NEONATOLOGY',
  GENERAL_MEDICINE = 'GENERAL_MEDICINE',
  GYNECOLOGY = 'GYNECOLOGY',
  SEXUAL_REPRODUCTIVE_HEALTH = 'SEXUAL_REPRODUCTIVE_HEALTH',
  OBSTETRICS = 'OBSTETRICS',
  PEDIATRICS = 'PEDIATRICS',
  NUTRITION = 'NUTRITION',
  PHYSIOTHERAPY = 'PHYSIOTHERAPY',
  KINESIOLOGY = 'KINESIOLOGY',
  POSTPARTUM_REHABILITATION = 'POSTPARTUM_REHABILITATION',

  // Wellness & Movement
  SPORTS = 'SPORTS',
  MEDITATION = 'MEDITATION',

  // Organizational & Corporate
  GENDER_CONSULTING = 'GENDER_CONSULTING',
  ORGANIZATIONAL_CULTURE = 'ORGANIZATIONAL_CULTURE',
  DEI_GENDER = 'DEI_GENDER',
  PUBLIC_POLICIES = 'PUBLIC_POLICIES',
  WORKSHOP_FACILITATION = 'WORKSHOP_FACILITATION',
  COMMUNICATION_CONTENT = 'COMMUNICATION_CONTENT',

  // Technology
  UX_DESIGN = 'UX_DESIGN',
  TECHNOLOGY_AI_DATA = 'TECHNOLOGY_AI_DATA',

  // Other
  OTHER = 'OTHER',
}
