export enum WorkModalityEnum {
  FULL_TIME_PRESENTIAL = 'FULL_TIME_PRESENTIAL',
  FULL_TIME_HYBRID = 'FULL_TIME_HYBRID',
  FULL_TIME_REMOTE = 'FULL_TIME_REMOTE',
  PART_TIME_PRESENTIAL = 'PART_TIME_PRESENTIAL',
  PART_TIME_HYBRID = 'PART_TIME_HYBRID',
  PART_TIME_REMOTE = 'PART_TIME_REMOTE',
  OTHER = 'OTHER',
}

